# Generated by Django 5.2.5 on 2025-08-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_category_category_slug_alter_tag_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soccial_name', models.CharField(default='', max_length=200)),
                ('soccial_icon', models.TextField(default='')),
                ('soccial_link', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
