# Generated by Django 5.2.5 on 2025-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_soccial_icon_social_social_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(default='', max_length=200, null=True, unique=True),
        ),
    ]
