# Generated by Django 5.2.5 on 2025-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_blog_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
