# Generated by Django 5.2.5 on 2025-08-25 18:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
