# Generated by Django 5.2.5 on 2025-08-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='soccial_icon',
            new_name='social_icon',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='soccial_link',
            new_name='social_link',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='soccial_name',
            new_name='social_name',
        ),
    ]
