# Generated by Django 5.2.5 on 2025-08-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=200)),
                ('site_tagline', models.CharField(default='', max_length=200)),
                ('site_description', models.TextField(blank=True, default='', null=True)),
                ('site_meta_keywords', models.TextField(blank=True, default='', null=True)),
                ('site_meta_description', models.TextField(blank=True, default='', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
    ]
